# Generated by Django 2.1.1 on 2018-09-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180909_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Блог пост', 'verbose_name_plural': 'Блог посты'},
        ),
    ]
